USE [TalksDB];

INSERT INTO Disciplines([DisciplineName]) VALUES('Suspendisse'),
('a,'),
('magna.'),
('aptent'),
('In'),
('inceptos'),
('ut,'),
('sem,'),
('Nunc'),
('ac,'),
('mi.'),
('leo,'),
('fringilla'),
('et'),
('viverra.'),
('montes,'),
('malesuada'),
('nisl.'),
('non,'),
('tellus.'),
('quis,'),
('tincidunt'),
('libero'),
('elementum'),
('est'),
('quam'),
('Curabitur'),
('consequat'),
('sodales'),
('interdum.'),
('lectus'),
('ut,'),
('sit'),
('vel'),
('Nulla'),
('justo.'),
('leo.'),
('ut'),
('in,'),
('vitae'),
('congue'),
('quis'),
('posuere'),
('gravida'),
('ut,'),
('tortor'),
('Quisque'),
('interdum'),
('vel,'),
('luctus'),
('malesuada.'),
('Fusce'),
('sed'),
('orci'),
('vitae'),
('Cum'),
('et'),
('lacus.'),
('nec'),
('tristique'),
('neque'),
('mauris'),
('lorem,'),
('vitae'),
('Nunc'),
('Duis'),
('luctus'),
('Donec'),
('semper'),
('et,'),
('nec'),
('nunc'),
('Nulla'),
('Curabitur'),
('lacinia'),
('convallis'),
('malesuada'),
('scelerisque'),
('sollicitudin'),
('lobortis'),
('ligula.'),
('faucibus'),
('Mauris'),
('Fusce'),
('lorem'),
('magna.'),
('Suspendisse'),
('dis'),
('mauris'),
('scelerisque'),
('porta'),
('nibh.'),
('ut'),
('Integer'),
('sed'),
('velit.'),
('Donec'),
('In'),
('tellus'),
('in');




INSERT INTO Speakers([FirstName],[LastName],[Email],[Position],[Department],[Location]) VALUES
('Hermione','Pollard','lectus.quis@eu.org','Non Vestibulum Nec Limited','AR','Fort Smith'),
('Wylie','Chang','lectus@elit.net','Viverra Donec Tempus Incorporated','WI','Milwaukee'),
('Idona','Walter','non@pellentesque.net','Donec Associates','WY','Rock Springs'),
('Caryn','Horton','vitae.sodales@erateget.net','Maecenas Ornare Egestas PC','OK','Norman'),
('Elizabeth','Maynard','sagittis.Duis.gravida@tinciduntaliquam.net','Arcu Ac Orci Associates','HI','Honolulu'),
('Oliver','Christian','adipiscing.elit@Cras.net','Magna Industries','MS','Gulfport'),
('Meghan','Mckay','quis.accumsan.convallis@quis.org','Ultricies Adipiscing Corp.','IN','Gary'),
('Aidan','Trevino','magna@at.edu','Congue In Associates','TX','Austin'),
('Darius','Short','vel@velitAliquam.com','Integer Vulputate Associates','CT','New Haven'),
('Pascale','Sandoval','vehicula@Vestibulum.net','Non Foundation','LA','Lafayette'),
('Clio','Burks','et.libero.Proin@aliquet.com','Nunc LLC','LA','New Orleans'),
('Tiger','Irwin','Phasellus@nulla.co.uk','Ultrices PC','AZ','Chandler'),
('Serena','Hutchinson','porta@interdumCurabiturdictum.org','Penatibus Foundation','MS','Southaven'),
('Marah','Bryan','dui.nec.tempus@IntegerurnaVivamus.com','Viverra Donec Tempus Limited','ME','South Portland'),
('Wylie','Bonner','mi.felis@eu.com','Enim PC','MS','Jackson'),
('Lysandra','Riggs','risus@mus.net','Nec Ante Consulting','MD','Baltimore'),
('Brennan','Odonnell','amet@ligulaAeneaneuismod.ca','Non Ante Inc.','WI','Green Bay'),
('Addison','Wilkinson','mi.tempor@enimconsequat.net','Lacus Ut LLC','ID','Nampa'),
('Signe','Mosley','ante@Maurisnulla.org','Proin Vel Company','AL','Mobile'),
('Cheyenne','Barrera','aliquet.nec.imperdiet@dapibusquamquis.edu','Nam Company','VA','Virginia Beach'),
('Gabriel','Kemp','cursus.et@SednequeSed.ca','Suscipit Nonummy Consulting','MA','Cambridge'),
('Hoyt','Terry','natoque@Aliquam.co.uk','Vulputate Posuere Associates','WY','Wyoming'),
('Kaseem','Conrad','cursus.purus.Nullam@necleoMorbi.org','Fames Ac Industries','TN','Clarksville'),
('Forrest','Roberts','dictum.magna@idmollis.ca','Cursus Diam Institute','WI','Racine'),
('Callie','Sharp','aliquam.iaculis.lacus@bibendumsedest.ca','Nunc Corp.','LA','Baton Rouge'),
('Zenaida','Reilly','euismod@netusetmalesuada.net','Id Corporation','WI','Green Bay'),
('Francis','Mack','arcu@Quisquenonummyipsum.net','Nullam Suscipit Est Associates','VT','Colchester'),
('Dustin','Blackburn','dolor.Fusce.mi@justosit.edu','Arcu Incorporated','TN','Chattanooga'),
('Vance','Woods','Sed.id.risus@dui.ca','Nulla Corp.','ME','Auburn'),
('Phoebe','Sharp','Ut.sagittis@Nuncac.com','Morbi Company','UT','West Valley City'),
('Ezra','Rosario','a@odio.org','Justo Sit Consulting','FL','Tallahassee'),
('Burton','Horton','Vestibulum.ante@magnaPraesent.edu','Volutpat Nulla Company','CO','Denver'),
('Kaseem','Kemp','amet.dapibus.id@sitametdapibus.edu','Auctor Non Consulting','WA','Tacoma'),
('Macaulay','Dillard','libero.lacus@tellusidnunc.com','Lobortis Ultrices LLC','OH','Akron'),
('Caldwell','Cunningham','in@laciniamattisInteger.com','Nisl Corp.','OK','Lawton'),
('Garth','Hutchinson','sem.semper@odio.com','Imperdiet Non Vestibulum Industries','CA','San Diego'),
('Olympia','Wolf','tellus.eu.augue@purussapiengravida.ca','Eget Varius Ultrices Inc.','KS','Kansas City'),
('Lyle','Valentine','posuere@lorem.co.uk','Ullamcorper Duis Cursus Limited','KY','Covington'),
('Russell','Donovan','risus@egestas.net','Fringilla LLC','MI','Lansing'),
('Lilah','Wiggins','risus@sitamet.co.uk','Ut Pellentesque Eget LLC','VA','Norfolk'),
('Larissa','Morrison','lectus.a@Nuncac.co.uk','Tortor Nibh Company','FL','Jacksonville'),
('Cameron','Odonnell','ut.quam.vel@acorciUt.net','Etiam Vestibulum Industries','TN','Memphis'),
('Berk','Grant','est.tempor@sed.ca','Cras Pellentesque Consulting','WA','Bellevue'),
('Macon','Barnett','fringilla.ornare.placerat@Proin.com','Sem Industries','AZ','Glendale'),
('Sybill','Murray','turpis@erosturpisnon.com','Et Pede Limited','WI','Madison'),
('Nehru','Holcomb','nisl.sem.consequat@libero.com','Nascetur Corporation','MA','Lowell'),
('Sloane','Ochoa','turpis.egestas.Fusce@nostra.net','Nec Orci Donec PC','OK','Norman'),
('Amena','Hatfield','vitae@Maurisnondui.co.uk','Malesuada Consulting','OH','Columbus'),
('Lael','Knox','Sed.neque.Sed@Sednuncest.org','Orci Donec Nibh Company','MD','Annapolis'),
('Reed','Hart','lectus.a@Morbi.com','Tortor Dictum Eu Institute','KS','Overland Park'),
('Calvin','Bolton','dui.Fusce.aliquam@Duisacarcu.org','Donec Associates','MI','Lansing'),
('Rama','Emerson','arcu.Vivamus@tortorIntegeraliquam.ca','Aenean Egestas LLC','NV','Las Vegas'),
('Curran','Acevedo','amet.ultricies.sem@facilisis.net','Erat Ltd','OR','Portland'),
('Dorothy','Craig','mi@eu.net','Dictum Ltd','WY','Wyoming'),
('Tobias','Castro','euismod@ornare.ca','Morbi Sit LLC','VA','Newport News'),
('Brian','Blackburn','enim.Etiam@sociisnatoquepenatibus.ca','Turpis Industries','HI','Kapolei'),
('Naomi','Combs','risus.Donec@quamCurabiturvel.com','Eleifend Associates','LA','Metairie'),
('George','Beard','fermentum.arcu.Vestibulum@sedliberoProin.co.uk','Ut Corporation','KS','Olathe'),
('Tate','Haley','Ut.nec.urna@vulputaterisusa.co.uk','Urna Vivamus Molestie Ltd','TX','San Antonio'),
('Eliana','Holmes','enim.Sed.nulla@quis.ca','Orci Corporation','MS','Biloxi'),
('Jakeem','Curry','Nullam.feugiat@Integer.ca','Massa Lobortis Ultrices Institute','OR','Gresham'),
('Zephania','Weeks','amet.consectetuer.adipiscing@ipsum.com','Amet Consectetuer Adipiscing Incorporated','NV','Henderson'),
('Chaim','Oconnor','dictum.ultricies@atpede.ca','Varius Orci Inc.','OR','Hillsboro'),
('Shelly','Holden','Sed.dictum@neccursusa.ca','Feugiat Ltd','MN','Rochester'),
('Carl','Graham','sapien.Aenean@noncursusnon.ca','Eu Consulting','MT','Butte'),
('Hayley','Randall','nec.imperdiet.nec@mattis.com','Pellentesque Massa Corporation','KS','Olathe'),
('Breanna','Nash','conubia@penatibus.com','Urna Associates','OR','Hillsboro'),
('Holly','Blake','quis.pede@quismassaMauris.edu','Arcu Vestibulum Consulting','PA','Reading'),
('Reece','Steele','pretium.aliquet@cursus.org','Vel Vulputate LLC','IN','Evansville'),
('Adrian','Blevins','sociis.natoque@semut.net','Facilisis Eget Consulting','GA','Atlanta'),
('Adrian','Norman','placerat.orci@disparturient.org','Consequat Lectus Company','KS','Olathe'),
('Blaine','Norton','Aliquam@sitametmetus.edu','Penatibus Et Magnis PC','CO','Colorado Springs'),
('Yoshio','Reynolds','accumsan.convallis@enim.edu','Augue Scelerisque Limited','MA','Boston'),
('Berk','Ray','Integer@sempererat.ca','Amet Institute','CO','Fort Collins'),
('Hu','Stewart','Cras.dictum@tristiquepellentesque.edu','Parturient Incorporated','GA','Georgia'),
('Zorita','Kirk','amet.massa.Quisque@necorciDonec.com','Fermentum Metus LLP','MA','Springfield'),
('Kerry','Mayer','metus@Nullaeget.com','Sed Hendrerit A Incorporated','TN','Clarksville'),
('Naida','Singleton','vel@etrisus.edu','Tincidunt Neque PC','IL','Chicago'),
('Hammett','Day','enim@facilisiSedneque.co.uk','Maecenas Iaculis Corp.','AL','Tuscaloosa'),
('Jakeem','Hammond','ultrices@necligulaconsectetuer.com','Lacinia Limited','UT','West Valley City'),
('Avram','Lane','dolor.elit@vel.net','Vivamus PC','AL','Huntsville'),
('Colleen','Tate','Duis.cursus.diam@penatibusetmagnis.co.uk','Nec LLC','AL','Huntsville'),
('Iola','Ortega','porttitor.interdum@convalliserat.co.uk','Eu Inc.','IA','Davenport'),
('Quemby','Anderson','eget.massa.Suspendisse@commodo.ca','Fames Company','MI','Detroit'),
('Allen','Gilliam','non.cursus.non@dapibusligula.ca','Praesent Eu LLC','NE','Grand Island'),
('Audrey','Nelson','dolor.vitae@laciniamattis.com','Magnis Dis LLC','CO','Aurora'),
('Amanda','Leonard','varius.orci@Aeneaneuismod.ca','Donec Institute','OR','Eugene'),
('Reuben','Gibson','eget.tincidunt@risusDuisa.net','Nec Urna Et LLP','AZ','Glendale'),
('Vaughan','Howard','nisl.sem.consequat@pedenecante.com','Lobortis LLP','MS','Biloxi'),
('Delilah','Trevino','risus.Donec.nibh@tellusAeneanegestas.edu','Urna Et Arcu Institute','OK','Norman'),
('Florence','Mendoza','nibh.sit@magnis.com','Dictum Mi Inc.','CA','Los Angeles'),
('Michelle','Maldonado','ipsum.nunc.id@orciconsectetuer.com','Ut PC','AZ','Tucson'),
('Ryder','Oneill','eu@Integerinmagna.com','Aliquet Odio LLC','CA','San Diego'),
('Rahim','Burris','dolor.nonummy.ac@pedeacurna.co.uk','Non Corp.','DE','Dover'),
('Jamal','Young','Aliquam@egestasurnajusto.ca','In Limited','AL','Tuscaloosa'),
('Gretchen','Parks','est.ac.facilisis@gravida.co.uk','Et Rutrum Corp.','AZ','Tucson'),
('Chadwick','Abbott','ante.ipsum@Morbinon.org','Risus Odio Auctor Consulting','WI','Racine'),
('Brody','Simmons','Fusce@semmagnanec.edu','Mauris Suspendisse Company','HI','Kapolei'),
('Graham','Mosley','rhoncus@vulputatenisi.co.uk','A Sollicitudin Orci LLP','MO','Jefferson City'),
('Orla','Gay','orci.adipiscing@Donecluctus.co.uk','Sapien Industries','VA','Newport News');



INSERT INTO Talks([TalkDate],[Topic],[AdditionalDetail],[Speaker],[Discipline],[Location]) VALUES
('May 14, 2018','convallis dolor.','Nunc sed orci lobortis augue',85,19,'Palmerston'),
('Aug 11, 2018','Cum sociis','Ut semper pretium neque. Morbi',94,55,'Tübingen'),
('Jun 9, 2018','Mauris nulla.','dui. Suspendisse ac metus vitae',87,72,'Mandi Bahauddin'),
('Dec 6, 2018','lectus pede,','ridiculus mus. Proin vel arcu',99,12,'Cherain'),
('Nov 25, 2018','venenatis lacus.','et, magna. Praesent interdum ligula',3,99,'Seevetal'),
('Aug 17, 2017','Sed et','libero lacus, varius et, euismod',76,55,'Deline'),
('May 13, 2018','ultrices a,','varius et, euismod et, commodo',33,5,'Wemmel'),
('May 22, 2018','amet, faucibus','dolor. Fusce feugiat. Lorem ipsum',42,29,'Kapuskasing'),
('May 19, 2018','sit amet','parturient montes, nascetur ridiculus mus.',20,21,'Coalville'),
('Jun 2, 2017','nunc nulla','Sed et libero. Proin mi.',99,77,'Hildesheim'),
('Mar 25, 2018','consequat, lectus','Nunc sed orci lobortis augue',23,36,'Amravati'),
('Jan 6, 2017','faucibus id,','non, bibendum sed, est. Nunc',38,81,'Butzbach'),
('May 2, 2018','posuere cubilia','a tortor. Nunc commodo auctor',11,45,'Ponte nelle Alpi'),
('Mar 19, 2018','iaculis nec,','nec ligula consectetuer rhoncus. Nullam',6,11,'Taunusstein'),
('May 11, 2017','lorem, sit','malesuada vel, convallis in, cursus',97,20,'Outremont'),
('Jun 15, 2018','Mauris vel','nostra, per inceptos hymenaeos. Mauris',3,14,'Nocciano'),
('Feb 11, 2017','tellus. Aenean','tellus faucibus leo, in lobortis',13,3,'Cefalà Diana'),
('Nov 19, 2017','diam vel','ipsum. Suspendisse sagittis. Nullam vitae',99,22,'Santa Caterina Villarmosa'),
('May 18, 2018','hendrerit id,','eleifend, nunc risus varius orci,',47,19,'Codigoro'),
('Nov 20, 2018','vel quam','ornare. Fusce mollis. Duis sit',87,89,'Firenze'),
('Feb 10, 2017','dui nec','pede ac urna. Ut tincidunt',69,40,'Bromley'),
('Jan 9, 2017','libero et','malesuada. Integer id magna et',94,88,'Grand-Hallet'),
('Jan 13, 2017','Aliquam gravida','Sed neque. Sed eget lacus.',47,26,'Baden'),
('May 8, 2017','tempor erat','In tincidunt congue turpis. In',59,63,'Beringen'),
('Nov 12, 2018','lorem ipsum','amet, dapibus id, blandit at,',38,4,'Balurghat'),
('Aug 21, 2017','rhoncus. Proin','sem, consequat nec, mollis vitae,',60,68,'Kirkland'),
('Feb 10, 2018','metus sit','sagittis placerat. Cras dictum ultricies',1,4,'Burns Lake'),
('Aug 30, 2018','nec luctus','Curabitur sed tortor. Integer aliquam',96,3,'Geest-GŽrompont-Petit-RosiŽre'),
('Mar 19, 2017','sollicitudin commodo','nisl. Nulla eu neque pellentesque',72,30,'Mildura'),
('Sep 18, 2017','adipiscing non,','nulla ante, iaculis nec, eleifend',30,93,'Londerzeel'),
('Sep 15, 2017','sagittis semper.','interdum. Sed auctor odio a',58,18,'Polcenigo'),
('Dec 10, 2017','tempus eu,','Vivamus non lorem vitae odio',26,64,'Castlegar'),
('Jul 27, 2018','a felis','commodo ipsum. Suspendisse non leo.',84,40,'Huasco'),
('Jun 3, 2017','libero mauris,','ipsum. Suspendisse non leo. Vivamus',90,31,'Ghlin'),
('Jul 16, 2017','vel, convallis','Integer tincidunt aliquam arcu. Aliquam',94,31,'Montgomery'),
('Sep 30, 2018','natoque penatibus','Aenean gravida nunc sed pede.',11,27,'Vallepietra'),
('Feb 11, 2018','ac orci.','dui nec urna suscipit nonummy.',17,10,'Gaithersburg'),
('Sep 19, 2017','gravida. Aliquam','ridiculus mus. Proin vel arcu',58,72,'Kuşadası'),
('Aug 11, 2018','Morbi vehicula.','a mi fringilla mi lacinia',45,88,'Mostazal'),
('Aug 7, 2017','Nam ligula','sem. Nulla interdum. Curabitur dictum.',82,91,'Lives-sur-Meuse'),
('Dec 18, 2017','et magnis','Pellentesque ut ipsum ac mi',63,81,'Outremont'),
('May 9, 2017','risus. Quisque','tempor erat neque non quam.',14,20,'Runcorn'),
('Feb 13, 2017','iaculis enim,','faucibus leo, in lobortis tellus',36,63,'Wood Buffalo'),
('Apr 12, 2017','lorem lorem,','vel, vulputate eu, odio. Phasellus',66,89,'Ch‰telineau'),
('Jul 21, 2017','neque venenatis','Quisque varius. Nam porttitor scelerisque',78,46,'Ludwigshafen'),
('Dec 20, 2017','nulla ante,','dictum eleifend, nunc risus varius',62,3,'Georgia'),
('Nov 20, 2018','ultrices posuere','eu neque pellentesque massa lobortis',23,68,'Hove'),
('May 10, 2018','ultrices a,','sed pede. Cum sociis natoque',80,19,'Gonars'),
('May 29, 2017','tellus, imperdiet','In condimentum. Donec at arcu.',10,74,'Sint-Stevens-Woluwe'),
('Jul 30, 2018','cursus vestibulum.','dictum. Proin eget odio. Aliquam',10,92,'Southwell'),
('Feb 8, 2017','Ut nec','Ut tincidunt vehicula risus. Nulla',90,83,'Rachecourt'),
('Mar 19, 2017','In ornare','est, vitae sodales nisi magna',4,12,'Plymouth'),
('Jul 2, 2017','aliquet molestie','iaculis aliquet diam. Sed diam',93,49,'Cariboo Regional District'),
('Feb 14, 2017','dui nec','nulla. In tincidunt congue turpis.',98,98,'Corral'),
('Sep 27, 2017','turpis vitae','arcu. Aliquam ultrices iaculis odio.',67,19,'Angol'),
('Mar 5, 2017','consectetuer euismod','commodo ipsum. Suspendisse non leo.',66,35,'Lanester'),
('Jul 23, 2018','lorem ac','sed, hendrerit a, arcu. Sed',63,20,'Lokeren'),
('Jul 29, 2018','a sollicitudin','luctus. Curabitur egestas nunc sed',96,98,'Guwahati'),
('Mar 31, 2018','purus sapien,','ultricies sem magna nec quam.',100,21,'Rapone'),
('Nov 26, 2018','sit amet','nisl. Nulla eu neque pellentesque',2,57,'La Thuile'),
('Apr 10, 2018','erat vel','auctor quis, tristique ac, eleifend',57,83,'Trowbridge'),
('Nov 12, 2018','dapibus gravida.','egestas lacinia. Sed congue, elit',30,59,'Baton Rouge'),
('Apr 18, 2018','luctus, ipsum','ut, nulla. Cras eu tellus',77,63,'Kungälv'),
('May 17, 2018','eu, ultrices','mollis. Duis sit amet diam',77,5,'Borno'),
('Jun 25, 2018','ipsum primis','magna tellus faucibus leo, in',53,5,'Villa Faraldi'),
('Aug 27, 2018','nisl sem,','justo. Proin non massa non',19,65,'Pondicherry'),
('Sep 23, 2018','Donec tempus,','vel sapien imperdiet ornare. In',94,74,'Shippagan'),
('Jan 3, 2017','consequat purus.','libero. Integer in magna. Phasellus',34,26,'Gibsons'),
('Aug 22, 2017','consequat, lectus','lectus rutrum urna, nec luctus',34,39,'Neu-Isenburg'),
('Nov 11, 2017','nibh vulputate','egestas. Aliquam nec enim. Nunc',37,18,'FlŽnu'),
('Jul 29, 2017','Vestibulum ante','pede. Nunc sed orci lobortis',67,52,'Zwevegem'),
('Oct 31, 2018','Mauris vestibulum,','Nunc laoreet lectus quis massa.',80,47,'Penrith'),
('May 16, 2018','urna. Nullam','taciti sociosqu ad litora torquent',18,32,'Constitución'),
('Sep 29, 2018','sem, vitae','vulputate, risus a ultricies adipiscing,',89,14,'Cache Creek'),
('Jul 16, 2017','ullamcorper viverra.','Suspendisse dui. Fusce diam nunc,',2,53,'Cap-Rouge'),
('Oct 22, 2017','molestie tellus.','dapibus ligula. Aliquam erat volutpat.',81,83,'Kędzierzyn-Koźle'),
('Jul 2, 2018','sed libero.','et ipsum cursus vestibulum. Mauris',98,87,'Vidisha'),
('Mar 24, 2018','ante. Maecenas','Mauris blandit enim consequat purus.',74,12,'Kasterlee'),
('Jul 24, 2017','Nullam lobortis','nunc id enim. Curabitur massa.',73,48,'Barranca'),
('Jan 3, 2018','velit dui,','Pellentesque habitant morbi tristique senectus',20,96,'Şanlıurfa'),
('Oct 6, 2017','ultrices sit','arcu ac orci. Ut semper',75,40,'Lelystad'),
('Sep 29, 2018','blandit mattis.','Phasellus nulla. Integer vulputate, risus',11,89,'Silvassa'),
('Mar 14, 2018','leo elementum','Etiam bibendum fermentum metus. Aenean',48,61,'Boussu-lez-Walcourt'),
('Feb 9, 2017','turpis non','primis in faucibus orci luctus',95,73,'Crotta d''Adda'),
('Apr 24, 2018','quis, tristique','Aliquam erat volutpat. Nulla dignissim.',44,12,'Butzbach'),
('Jan 27, 2018','lectus sit','Fusce aliquet magna a neque.',92,92,'Sparwood'),
('Mar 9, 2017','bibendum fermentum','eget, venenatis a, magna. Lorem',16,90,'Bruderheim'),
('Jan 11, 2018','sit amet','risus. Quisque libero lacus, varius',90,80,'Speyer'),
('May 3, 2018','cubilia Curae;','dui, semper et, lacinia vitae,',100,49,'Pointe-Claire'),
('May 7, 2018','Pellentesque ultricies','vel, faucibus id, libero. Donec',1,8,'Lisciano Niccone'),
('Jan 21, 2017','ut eros','hendrerit. Donec porttitor tellus non',31,30,'Barddhaman'),
('May 22, 2017','Curabitur ut','turpis vitae purus gravida sagittis.',26,70,'Gladstone'),
('Nov 23, 2017','eu, ultrices','eu dui. Cum sociis natoque',25,6,'Panketal'),
('Nov 18, 2017','vitae purus','congue. In scelerisque scelerisque dui.',6,48,'North Las Vegas'),
('Nov 28, 2017','massa. Mauris','ante lectus convallis est, vitae',42,64,'Gubbio'),
('Mar 18, 2017','eu nibh','vulputate, posuere vulputate, lacus. Cras',52,88,'Haldia'),
('Feb 25, 2017','turpis. Aliquam','egestas. Sed pharetra, felis eget',53,25,'Oostkamp'),
('Feb 8, 2017','eget, dictum','Nulla tempor augue ac ipsum.',23,27,'Dehradun'),
('Nov 9, 2017','non enim.','elit fermentum risus, at fringilla',70,70,'Trois-Rivières'),
('May 28, 2018','mi eleifend','odio. Aliquam vulputate ullamcorper magna.',99,93,'Ayr');
